-- MySQL Script generated by MySQL Workbench
-- Dom 19 Nov 2017 15:41:36 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gre_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gre_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gre_app` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gre_app` ;

-- -----------------------------------------------------
-- Table `gre_app`.`ufs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`ufs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inep_codigo` INT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`municipios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf_id` INT NOT NULL,
  `inep_codigo` INT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_ufs1_idx` (`uf_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_ufs1_idx` (`uf_id` ASC),
  CONSTRAINT `fk_municipio_uf`
    FOREIGN KEY (`uf_id`)
    REFERENCES `gre_app`.`ufs` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_municipio_uf`
    FOREIGN KEY (`uf_id`)
    REFERENCES `gre_app`.`ufs` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`distritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `municipio_id` INT NOT NULL,
  `inep_codigo` INT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_distrito_municipio_idx` (`municipio_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_distrito_municipio_idx` (`municipio_id` ASC),
  CONSTRAINT `fk_distrito_municipio`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `gre_app`.`municipios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_distrito_municipio`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `gre_app`.`municipios` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`escola_situacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escola_situacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordem` INT NOT NULL DEFAULT 0,
  `nome` VARCHAR(30) NOT NULL COMMENT 'Descrição curta da situação da Escola.',
  `descricao` TEXT NOT NULL COMMENT 'Descrição longa da situação.',
  `_webapp_css_class` VARCHAR(20) NULL COMMENT 'Classe CSS para estilização na aplicação web',
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Situações possíveis para uma Escola.';


-- -----------------------------------------------------
-- Table `gre_app`.`escolas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escolas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rede` TINYINT(1) NOT NULL COMMENT 'Indica se a escola pertence à rede mantida pelo GRE',
  `inep_codigo` VARCHAR(8) NOT NULL,
  `situacao_id` INT NOT NULL,
  `nome_longo` VARCHAR(100) NOT NULL,
  `nome_curto` VARCHAR(50) NOT NULL,
  `nome_juridico` VARCHAR(200) NOT NULL,
  `endereco_cep` VARCHAR(8) NOT NULL,
  `endereco_distrito_id` INT NOT NULL,
  `endereco_logradouro` VARCHAR(100) NOT NULL,
  `endereco_numero` VARCHAR(10) NULL,
  `endereco_complemento` VARCHAR(50) NULL,
  `endereco_bairro` VARCHAR(60) NOT NULL,
  `infra_agua_filtrada` TINYINT(1) NOT NULL DEFAULT 1,
  `infra_agua_abast_publica` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_agua_abast_poco` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_agua_abast_cacimba` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_agua_abast_fonte` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_agua_abast_inexistente` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_energia_abast_publica` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_energia_abast_gerador` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_energia_abast_outros` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_energia_abast_inexistente` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_esgoto_rede` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_esgoto_fossa` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_esgoto_inexistente` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_coleta` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_queima` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_joga` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_recicla` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_enterra` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_lixo_outros` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_almoxarifado` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_alojamento_aluno` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_alojamento_professor` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_area_verde` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_auditorio` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_banheiro_acessivel` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_banheiro_infantil` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_banheiro_chuveiro` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_banheiro_dentro` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_banheiro_fora` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_bercario` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_biblioteca` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_cozinha` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_vias_deficientes` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_despensa` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_lab_ciencias` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_lab_informatica` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_lavanderia` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_parque_infantil` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_patio_coberto` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_patio_descoberto` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_quadra_coberta` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_quadra_descoberta` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_refeitorio` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_sala_leitura` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_sala_diretoria` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_sala_professores` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_sala_recursos` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_sala_secretaria` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_dep_nenhuma` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_equip_parabolica` INT NOT NULL DEFAULT 0,
  `infra_equip_dvd` INT NOT NULL DEFAULT 0,
  `infra_equip_som` INT NOT NULL DEFAULT 0,
  `infra_equip_tv` INT NOT NULL DEFAULT 0,
  `infra_equip_copiadora` INT NOT NULL DEFAULT 0,
  `infra_equip_fax` INT NOT NULL DEFAULT 0,
  `infra_equip_impressora` INT NOT NULL DEFAULT 0,
  `infra_equip_impressora_multi` INT NOT NULL DEFAULT 0,
  `infra_equip_filmadora` INT NOT NULL DEFAULT 0,
  `infra_equip_projetor` INT NOT NULL DEFAULT 0,
  `infra_equip_retroprojetor` INT NOT NULL DEFAULT 0,
  `infra_equip_videocassete` INT NOT NULL DEFAULT 0,
  `infra_equip_computador` INT NOT NULL DEFAULT 0,
  `infra_pc_alunos` INT NOT NULL DEFAULT 0,
  `infra_pc_admin` INT NOT NULL DEFAULT 0,
  `infra_internet` TINYINT(1) NOT NULL DEFAULT 0,
  `infra_internet_banda_larga` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Indica se a escola pertence à rede de ensino gerenciada pelo GRE',
  `leg_criacao` VARCHAR(100) NULL,
  `leg_denominacao` VARCHAR(100) NULL,
  `fone_1` VARCHAR(20) NULL,
  `fone_2` VARCHAR(20) NULL,
  `fone_3` VARCHAR(20) NULL,
  `fone_4` VARCHAR(20) NULL,
  `email` VARCHAR(200) NULL,
  `website` VARCHAR(200) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_escola_escola_situacao_idx` (`situacao_id` ASC),
  INDEX `fk_escola_endereco_distrito_idx` (`endereco_distrito_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_escola_escola_situacao_idx` (`situacao_id` ASC),
  INDEX `fk_escola_endereco_distrito_idx` (`endereco_distrito_id` ASC),
  CONSTRAINT `fk_escola_endereco_distrito`
    FOREIGN KEY (`endereco_distrito_id`)
    REFERENCES `gre_app`.`distritos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_escola_situacao`
    FOREIGN KEY (`situacao_id`)
    REFERENCES `gre_app`.`escola_situacoes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_endereco_distrito`
    FOREIGN KEY (`endereco_distrito_id`)
    REFERENCES `gre_app`.`distritos` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_escola_situacao`
    FOREIGN KEY (`situacao_id`)
    REFERENCES `gre_app`.`escola_situacoes` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Escolas da rede';


-- -----------------------------------------------------
-- Table `gre_app`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inep_codigo` INT NULL,
  `alpha2` VARCHAR(2) NULL,
  `alpha3` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`escola_local_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escola_local_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária',
  `ordem` INT NOT NULL DEFAULT 0 COMMENT 'Ordenação dos resultados',
  `nome` VARCHAR(60) NOT NULL COMMENT 'Nome do local de funcionamento da escola',
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`predio_ocupacao_formas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`predio_ocupacao_formas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária\n',
  `ordem` INT NOT NULL DEFAULT 0,
  `nome` VARCHAR(40) NOT NULL COMMENT 'Nome da forma de ocupação do prédio da escola',
  `created` DATETIME NULL COMMENT 'Data criação do registro',
  `modified` DATETIME NULL COMMENT 'Data da última modificação do registro',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Indica se o registro foi marcado como excluído',
  PRIMARY KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '‭‫Formas de ocupação de do prédio da escola';


-- -----------------------------------------------------
-- Table `gre_app`.`escola_locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escola_locais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escola_id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `escola_local_tipo_id` INT NOT NULL,
  `predio_ocupacao_forma_id` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_escola_locais_escolas_idx` (`escola_id` ASC),
  INDEX `fk_escola_locais_escola_local_tipos_idx` (`escola_local_tipo_id` ASC),
  INDEX `fk_escola_local_predio_ocupacao_forma_idx` (`predio_ocupacao_forma_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_escola_locais_escolas_idx` (`escola_id` ASC),
  INDEX `fk_escola_locais_escola_local_tipos_idx` (`escola_local_tipo_id` ASC),
  INDEX `fk_escola_local_predio_ocupacao_forma_idx` (`predio_ocupacao_forma_id` ASC),
  CONSTRAINT `fk_escola_local_escola`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_escola_local_tipo`
    FOREIGN KEY (`escola_local_tipo_id`)
    REFERENCES `gre_app`.`escola_local_tipos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_predio_ocupacao_forma`
    FOREIGN KEY (`predio_ocupacao_forma_id`)
    REFERENCES `gre_app`.`predio_ocupacao_formas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_escola`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_escola_local_tipo`
    FOREIGN KEY (`escola_local_tipo_id`)
    REFERENCES `gre_app`.`escola_local_tipos` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_predio_ocupacao_forma`
    FOREIGN KEY (`predio_ocupacao_forma_id`)
    REFERENCES `gre_app`.`predio_ocupacao_formas` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`reconhecimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`reconhecimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escola_id` INT NOT NULL,
  `curso` VARCHAR(60) NOT NULL,
  `ato` VARCHAR(60) NOT NULL,
  `validade` DATE NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_reconhecimentos_escolas1_idx` (`escola_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_reconhecimentos_escolas1_idx` (`escola_id` ASC),
  CONSTRAINT `fk_reconhecimentos_escolas1`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reconhecimentos_escolas1`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Reconhecimentos de cursos';


-- -----------------------------------------------------
-- Table `gre_app`.`escola_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escola_salas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escola_local_id` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `capacidade` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_sala_escola_local_idx` (`escola_local_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_sala_escola_local_idx` (`escola_local_id` ASC),
  CONSTRAINT `fk_sala_escola_local`
    FOREIGN KEY (`escola_local_id`)
    REFERENCES `gre_app`.`escola_locais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sala_escola_local`
    FOREIGN KEY (`escola_local_id`)
    REFERENCES `gre_app`.`escola_locais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gre_app`.`escola_local_compartilhamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gre_app`.`escola_local_compartilhamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escola_local_id` INT NOT NULL,
  `escola_id` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_escola_local_compartilhamento_escola_local_idx` (`escola_local_id` ASC),
  INDEX `fk_escola_local_compartilhamento_escola_idx` (`escola_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_escola_local_compartilhamento_escola_local_idx` (`escola_local_id` ASC),
  INDEX `fk_escola_local_compartilhamento_escola_idx` (`escola_id` ASC),
  CONSTRAINT `fk_escola_local_compartilhamento_escola_local`
    FOREIGN KEY (`escola_local_id`)
    REFERENCES `gre_app`.`escola_locais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_compartilhamento_escola`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_compartilhamento_escola`
    FOREIGN KEY (`escola_id`)
    REFERENCES `gre_app`.`escolas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escola_local_compartilhamento_escola_local`
    FOREIGN KEY (`escola_local_id`)
    REFERENCES `gre_app`.`escola_locais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
