<?php

return [
    'Icons' => [
        'alunos'        => 'fa fa-fw fa-users',
        'aviso'         => 'fa fa-fw fa-exclamation-circle',
        'cadastrar'     => 'fa fa-fw fa-plus',
        'caret'         => 'fa fa-fw fa-caret-down',
        'cancelar'      => 'fa fa-fw fa-times',
        'compartilhar'  => 'fa fa-fw fa-share-alt-square',
        'contato'       => 'fa fa-fw fa-phone-square',
        'dependencias'  => 'fa fa-fw fa-th',
        'diario'        => 'fa fa-fw fa-address-book',
        'educacao'      => 'fa fa-fw fa-graduation-cap',
        'editar'        => 'fa fa-fw fa-edit',
        'equipamento'   => 'fa fa-fw fa-television',
        'erro'          => 'fa fa-fw fa-ban',
        'escola'        => 'fa fa-fw fa-home',
        'excluir'       => 'fa fa-fw fa-trash',
        'exercicio'     => 'fa fa-fw fa-circle-o-notch',
        'imprimir'      => 'fa fa-fw fa-print',
        'info'          => 'fa fa-fw fa-info-circle',
        'infra'         => 'fa fa-fw fa-building-o',
        'lei'           => 'fa fa-fw fa-book',
        'lista'         => 'fa fa-fw fa-list',
        'locais'        => 'fa fa-fw fa-home',
        'matricula'     => 'fa fa-fw fa-id-card',
        'painel'        => 'fa fa-fw fa-th-large',
        'pesquisar'     => 'fa fa-fw fa-search',
        'professor'     => 'fa fa-fw fa-graduation-cap',
        'profissionais' => 'fa fa-fw fa-users',
        'profissional'  => 'fa fa-fw fa-user',
        'rede'          => 'fa fa-fw fa-sitemap',
        'rh'            => 'fa fa-fw fa-users',
        'secretaria'    => 'fa fa-fw fa-folder',
        'salvar'        => 'fa fa-fw fa-check-circle',
        'sistema'       => 'fa fa-fw fa-cogs',
        'sucesso'       => 'fa fa-fw fa-check-square-o',
        'triste'        => 'fa fa-fw fa-frown-o',
        'voltar'        => 'fa fa-fw fa-arrow-left',
    ],
];
